name: CI

on:
    push:
        branches: [main]
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '10.0.x'
            - name: Build
              run: dotnet build
            - name: Test
              run: dotnet test
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: |
                    ghcr.io/${{ github.repository_owner }}/leave_management-api:latest
                    ghcr.io/${{ github.repository_owner }}/leave_management-api:${{ github.sha }}
